FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    lshw \
    iputils-ping \
    iproute2 \
    traceroute \
    dnsutils \
    net-tools \
    iproute2 \
    systemd \
    htop \
    lsof \
    sysstat

CMD ["/bin/bash"]